version: "3.8"

services:
  # KAFKA INFRASTRUCTURE
  pinnacle-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks: [pinnacle-network]

  pinnacle-kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - pinnacle-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: pinnacle-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pinnacle-kafka:9092,PLAINTEXT_INTERNAL://pinnacle-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks: [pinnacle-network]
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:29092 --list
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  pinnacle-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "4790:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: pinnacle
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: pinnacle-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: pinnacle-zookeeper:2181
    depends_on:
      - pinnacle-kafka
    networks: [pinnacle-network]

  pinnacle-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for live updates
      - ./frontend:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:4700/api/v1
      - NEXT_INTERNAL_API_URL=http://pinnacle-gateway:8080/api/v1
    command: npm run dev
    networks: [pinnacle-network]
    depends_on:
      - pinnacle-gateway
  # GATEWAY (Go)
  pinnacle-gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - REDIS_HOST=pinnacle-redis
      - REDIS_PORT=6379
      - AUTH_SERVICE_URL=pinnacle-auth-service:4460
      - USERS_SERVICE_URL=pinnacle-users-service:4450
      - OUTCOMES_SERVICE_URL=pinnacle-outcomes-service:4440
      - BOARDS_SERVICE_URL=pinnacle-boards-service:4470
    volumes:
      - ./backend/gateway:/app
      - go-modules:/go/pkg/mod
    command: go run cmd/api/main.go
    ports:
      - "4700:8080"
    depends_on:
      - pinnacle-redis
      - pinnacle-auth-service
      - pinnacle-users-service
      - pinnacle-outcomes-service
    networks: [pinnacle-network]

  # NESTJS MICROSERVICES
  pinnacle-auth-service:
    build:
      context: ./backend/services/nestjs-services
      dockerfile: Dockerfile.dev
      args:
        SERVICE_NAME: auth-service
    env_file:
        - ./backend/services/nestjs-services/apps/auth-service/.env
    volumes:
      - ./backend/services/nestjs-services:/app
      - /app/node_modules
      - /app/apps/auth-service/node_modules
    ports:
      - "4460:4460"
    depends_on:
      - pinnacle-auth-service-db
      - pinnacle-redis
    networks: [pinnacle-network]

  pinnacle-users-service:
    build:
      context: ./backend/services/nestjs-services
      dockerfile: Dockerfile.dev
      args:
        SERVICE_NAME: users-service
    env_file:
    - ./backend/services/nestjs-services/apps/users-service/.env
    volumes:
      - ./backend/services/nestjs-services:/app
      - /app/node_modules
      - /app/apps/users-service/node_modules
    ports:
      - "4450:4450"
    depends_on:
      - pinnacle-users-service-db
      - pinnacle-redis
    networks: [pinnacle-network]

  pinnacle-outcomes-service:
    build:
      context: ./backend/services/nestjs-services
      dockerfile: Dockerfile.dev
      args:
        SERVICE_NAME: outcomes-service
    env_file:
    - ./backend/services/nestjs-services/apps/outcomes-service/.env
    volumes:
      - ./backend/services/nestjs-services:/app
      - /app/node_modules
      - /app/apps/outcomes-service/node_modules
    ports:
      - "4440:4440"
      - "4441:4441"
    depends_on:
      pinnacle-kafka:
        condition: service_healthy
      pinnacle-outcomes-service-db:
        condition: service_started
      pinnacle-redis:
        condition: service_started

    networks: [pinnacle-network]

  pinnacle-notifications-service:
    build:
      context: ./backend/services/nestjs-services
      dockerfile: Dockerfile.dev
      args:
        SERVICE_NAME: notifications-service
    env_file:
    - ./backend/services/nestjs-services/apps/notifications-service/.env
    volumes:
      - ./backend/services/nestjs-services:/app
      - /app/node_modules
      - /app/apps/notifications-service/node_modules
    ports:
      - "4470:4470"
    depends_on:
      pinnacle-kafka:
        condition: service_healthy
      pinnacle-notifications-service-db:
        condition: service_started
      pinnacle-redis:
        condition: service_started

    networks: [pinnacle-network]
  # DATABASES


  pinnacle-auth-service-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - dbdata_auth_service:/var/lib/postgresql/data
      - ./docker/config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4462:5432"
    networks: [pinnacle-network]

  pinnacle-users-service-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - dbdata_users_service:/var/lib/postgresql/data
      - ./docker/config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4452:5432"
    networks: [pinnacle-network]

  pinnacle-outcomes-service-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outcomes
    volumes:
      - dbdata_outcomes_service:/var/lib/postgresql/data
      - ./docker/config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4442:5432"
    networks: [pinnacle-network]
  pinnacle-notifications-service-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    volumes:
      - dbdata_notifications_service:/var/lib/postgresql/data
      - ./docker/config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4472:5432"
    networks: [pinnacle-network]
  # UTILITIES

  pinnacle-adminer:
    image: adminer:latest
    ports:
      - "4780:8080"
    networks: [pinnacle-network]

  pinnacle-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks: [pinnacle-network]

networks:
  pinnacle-network:
    driver: bridge
    name: pinnacle-network
  observer:
    external: true

volumes:
  dbdata:
  dbdata_outcomes_service:
  dbdata_users_service:
  dbdata_auth_service:
  dbdata_notifications_service:
  redisdata:
  go-modules:
  zookeeper-data:
  zookeeper-log:
  kafka-data: